### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by to175** [Infuzion/DDUYF#1]
I did nothing, here is the error :
(beging at the end !)

[20:48:39]  [Server thread/WARN] : at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[20:48:39]  [Server thread/WARN] : at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
[20:48:39]  [Server thread/WARN] : at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:608)
[20:48:39]  [Server thread/WARN] : at org.bukkit.craftbukkit.v1_7_R4.CraftWorld.save(CraftWorld.java:695)
[20:48:39]  [Server thread/WARN] : at net.minecraft.server.v1_7_R4.WorldServer.save(WorldServer.java:799)
[20:48:39]  [Server thread/WARN] : at net.minecraft.server.v1_7_R4.WorldServer.a(WorldServer.java:826)
[20:48:39]  [Server thread/WARN] : at net.minecraft.server.v1_7_R4.World.G(World.java:2859)
[20:48:39]  [Server thread/WARN] : at net.minecraft.server.v1_7_R4.WorldNBTStorage.checkSession(WorldNBTStorage.java:78)
[20:48:39]  [Server thread/WARN] : net.minecraft.server.v1_7_R4.ExceptionWorldConflict: Failed to check session lock for world located at ./plot, aborting. Stop the server and delete the session.lock in this world to prevent further issues.
...     15 more
[Erreur Java]   org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit.jar:git-Spigot-1642]
[Erreur Java]   java.lang.reflect.Method.invoke(Method.java:601) ~[?:1.7.0]
[Erreur Java]   sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0]
[Erreur Java]   sun.reflect.GeneratedMethodAccessor577.invoke(Unknown Source) ~[?:?]
[Erreur Java]   infuzion.dduyf.DDUYF.onBlockBreak(DDUYF.java:203) ~[?:?]
[Erreur Java]   infuzion.dduyf.DDUYF.permission(DDUYF.java:130) ~[?:?]
Caused  by: java.lang.NullPointerException
[Erreur Java]   net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Spigot-1642]
[Erreur Java]   net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [craftbukkit.jar:git-Spigot-1642]
[Erreur Java]   net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [craftbukkit.jar:git-Spigot-1642]
[Erreur Java]   net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [craftbukkit.jar:git-Spigot-1642]
[Erreur Java]   net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [craftbukkit.jar:git-Spigot-1642]
[Erreur Java]   net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [craftbukkit.jar:git-Spigot-1642]
[Erreur Java]   net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [craftbukkit.jar:git-Spigot-1642]
[Erreur Java]   net.minecraft.server.v1_7_R4.PacketPlayInBlockDig.handle(PacketPlayInBlockDig.java:65) [craftbukkit.jar:git-Spigot-1642]
[Erreur Java]   net.minecraft.server.v1_7_R4.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:41) [craftbukkit.jar:git-Spigot-1642]
[Erreur Java]   net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:565) [craftbukkit.jar:git-Spigot-1642]
[Erreur Java]   net.minecraft.server.v1_7_R4.PlayerInteractManager.a(PlayerInteractManager.java:192) [craftbukkit.jar:git-Spigot-1642]
[Erreur Java]   net.minecraft.server.v1_7_R4.PlayerInteractManager.breakBlock(PlayerInteractManager.java:264) [craftbukkit.jar:git-Spigot-1642]
[Erreur Java]   org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [craftbukkit.jar:git-Spigot-1642]
[Erreur Java]   org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [craftbukkit.jar:git-Spigot-1642]
[Erreur Java]   org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-1642]
[Erreur Java]   org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit.jar:git-Spigot-1642]
[20:48:16]  [Server thread/ERROR] : Could not pass event BlockBreakEvent to DDUYF v1.1

**Comment by srikavin** [comment]
I have made a few fixes to it. The new file will be uploaded to Bukkit soon.

**Comment by srikavin** [comment]
Does the new file work?

**Comment by to175** [comment]
Where can I download it ??

**Comment by srikavin** [comment]
http://dev.bukkit.org/bukkit-plugins/dont-dig-under-your-feet/files/3-dduyf-v1-3/

**Comment by to175** [comment]
Yes, I said it doesn't work

**Comment by srikavin** [comment]
The latest version? Do you have another error log?

**Comment by to175** [comment]
I don't know you didn't answer on the bukkit page

**Comment by srikavin** [comment]
You have to rename the default group to the one in the list:
DDUYF:
  Options:
    ExemptOps: true
  Groups:
    Names:
    - citoyen
    default:
      Damage: 4.0
      Blocks: 3
      Permission: DDUYF.Groups.citoyen
      UsePermissions: false
      UseMessage: true
      Message: '&4 Shrapnel explodes under your feet causing you to take damage!'

to:

DDUYF:
  Options:
    ExemptOps: true
  Groups:
    Names:
    - citoyen
     citoyen:
      Damage: 4.0
      Blocks: 3
      Permission: DDUYF.Groups.citoyen
      UsePermissions: false
      UseMessage: true
      Message: '&4 Shrapnel explodes under your feet causing you to take damage!'

**Comment by to175** [comment]
[21:14:07] [Server thread/ERROR]: Could not pass event BlockBreakEvent to DDUYF v1.1
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit.jar:git-Spigot-1642]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-1642]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [craftbukkit.jar:git-Spigot-1642]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [craftbukkit.jar:git-Spigot-1642]
    at net.minecraft.server.v1_7_R4.PlayerInteractManager.breakBlock(PlayerInteractManager.java:264) [craftbukkit.jar:git-Spigot-1642]
    at net.minecraft.server.v1_7_R4.PlayerInteractManager.dig(PlayerInteractManager.java:118) [craftbukkit.jar:git-Spigot-1642]
    at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:552) [craftbukkit.jar:git-Spigot-1642]
    at net.minecraft.server.v1_7_R4.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:41) [craftbukkit.jar:git-Spigot-1642]
    at net.minecraft.server.v1_7_R4.PacketPlayInBlockDig.handle(PacketPlayInBlockDig.java:65) [craftbukkit.jar:git-Spigot-1642]
    at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [craftbukkit.jar:git-Spigot-1642]
    at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [craftbukkit.jar:git-Spigot-1642]
    at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [craftbukkit.jar:git-Spigot-1642]
    at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [craftbukkit.jar:git-Spigot-1642]
    at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [craftbukkit.jar:git-Spigot-1642]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [craftbukkit.jar:git-Spigot-1642]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Spigot-1642]
Caused by: java.lang.NullPointerException
    at infuzion.dduyf.DDUYF.getPlayerGroup(DDUYF.java:152) ~[?:?]
    at infuzion.dduyf.DDUYF.damage(DDUYF.java:166) ~[?:?]
    at infuzion.dduyf.DDUYF.onBlockBreak(DDUYF.java:192) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor844.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0]
    at java.lang.reflect.Method.invoke(Method.java:601) ~[?:1.7.0]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit.jar:git-Spigot-1642]
    ... 15 more

**Comment by srikavin** [comment]
Did you change your config file?

**Comment by to175** [comment]
Of course ...

**Comment by to175** [comment]
Do you want to create a config and send to me and test it on my server ?

**Comment by to175** [comment]
Always error, but it works like : 1 break 1 hit instead of 3 breaks 4 hit ...

**Comment by srikavin** [comment]
Should be fixed now.
